"""
_journal.py — append-only per-chunk journal for 02_generate_nanovllm.py.

manifest.json and wer_log.json used to be written only when a run finished,
so a crash mid-run (OOM, pod preemption, a runaway generation) lost every
completed chunk's bookkeeping even though the wavs themselves survived on
disk. The journal closes that gap: one JSON line is appended and flushed the
moment a chunk is accepted, so a resumed run (--start-at / --only-chunks) can
rebuild the finished chunks' WER entries and re-seed the duration baseline
without regenerating anything.

One record per line (manifest.json is already written durably before
generation starts, so the journal only needs the per-chunk quality data):

    {"id": 7, "wer": {...wer_log entry...}}

Later lines win when a chunk id repeats (a chunk regenerated by a later
partial run). A torn final line (crash mid-write) is skipped on read.
"""
import json
import os
from pathlib import Path

JOURNAL_NAME = "journal.jsonl"


def journal_path(out_dir: Path) -> Path:
    return out_dir / JOURNAL_NAME


def reset_journal(path: Path) -> None:
    """Remove the journal (start of a fresh full run: prior state is stale)."""
    try:
        path.unlink()
    except FileNotFoundError:
        pass


def append_chunk_record(path: Path, chunk_id: int, wer_entry: dict) -> None:
    """
    Append one chunk's record and flush it to disk immediately -- the whole
    point is surviving a crash later in the run.
    """
    record = {"id": int(chunk_id), "wer": wer_entry}
    line = json.dumps(record, ensure_ascii=False)
    with path.open("a", encoding="utf-8") as f:
        f.write(line + "\n")
        f.flush()
        os.fsync(f.fileno())


def read_chunk_records(path: Path) -> dict[int, dict]:
    """
    Return {chunk_id: record}, latest record winning per id. Malformed lines
    (typically a torn final line from a crash) are skipped, not fatal.
    """
    records: dict[int, dict] = {}
    if not path.exists():
        return records
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
            records[int(rec["id"])] = rec
        except (json.JSONDecodeError, KeyError, TypeError, ValueError):
            continue
    return records
