#!/usr/bin/env python3
"""
test_journal.py — regression tests for _journal.py, the append-only per-chunk
journal 02_generate_nanovllm.py uses so a crash mid-run doesn't lose the
completed chunks' bookkeeping.

Run after touching _journal.py:
    python scripts/test_journal.py
"""
import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _journal import (
    append_chunk_record,
    journal_path,
    read_chunk_records,
    reset_journal,
)


def _tmp_journal(tmp: str) -> Path:
    return journal_path(Path(tmp))


WER_ENTRY = {"id": 1, "wer": 0.05, "attempts": 1, "sec_per_word": 0.41,
             "duration_ok": True, "duration_reason": "ok"}


def test_missing_journal_reads_empty():
    with tempfile.TemporaryDirectory() as tmp:
        assert read_chunk_records(_tmp_journal(tmp)) == {}


def test_append_then_read_roundtrip():
    with tempfile.TemporaryDirectory() as tmp:
        path = _tmp_journal(tmp)
        append_chunk_record(path, 1, WER_ENTRY)
        records = read_chunk_records(path)
        assert set(records) == {1}
        assert records[1]["wer"] == WER_ENTRY


def test_later_record_wins_per_id():
    # A chunk regenerated by a later partial run appends a second line; the
    # newest one must win on read.
    with tempfile.TemporaryDirectory() as tmp:
        path = _tmp_journal(tmp)
        append_chunk_record(path, 1, WER_ENTRY)
        better = dict(WER_ENTRY, wer=0.0, attempts=2)
        append_chunk_record(path, 1, better)
        records = read_chunk_records(path)
        assert records[1]["wer"]["wer"] == 0.0
        assert records[1]["wer"]["attempts"] == 2


def test_torn_final_line_is_skipped():
    # A crash mid-write leaves a truncated last line; earlier records must
    # still be readable and the torn line must not raise.
    with tempfile.TemporaryDirectory() as tmp:
        path = _tmp_journal(tmp)
        append_chunk_record(path, 1, WER_ENTRY)
        append_chunk_record(path, 2, dict(WER_ENTRY, id=2))
        with path.open("a", encoding="utf-8") as f:
            f.write('{"id": 3, "wer": {"id"')  # torn mid-write
        records = read_chunk_records(path)
        assert set(records) == {1, 2}


def test_garbage_lines_are_skipped():
    with tempfile.TemporaryDirectory() as tmp:
        path = _tmp_journal(tmp)
        path.write_text('not json\n{"no_id": true}\n\n{"id": "not-an-int-x"}\n',
                        encoding="utf-8")
        assert read_chunk_records(path) == {}


def test_reset_removes_and_tolerates_missing():
    with tempfile.TemporaryDirectory() as tmp:
        path = _tmp_journal(tmp)
        reset_journal(path)  # nothing there yet: must not raise
        append_chunk_record(path, 1, WER_ENTRY)
        assert path.exists()
        reset_journal(path)
        assert not path.exists()
        assert read_chunk_records(path) == {}


def test_records_are_one_json_object_per_line():
    # The format contract: plain JSONL, independently parseable lines, so a
    # human can inspect it with head/tail/jq.
    with tempfile.TemporaryDirectory() as tmp:
        path = _tmp_journal(tmp)
        append_chunk_record(path, 1, WER_ENTRY)
        append_chunk_record(path, 2, dict(WER_ENTRY, id=2))
        lines = path.read_text(encoding="utf-8").splitlines()
        assert len(lines) == 2
        for line in lines:
            rec = json.loads(line)
            assert set(rec) == {"id", "wer"}


def main():
    tests = [
        test_missing_journal_reads_empty,
        test_append_then_read_roundtrip,
        test_later_record_wins_per_id,
        test_torn_final_line_is_skipped,
        test_garbage_lines_are_skipped,
        test_reset_removes_and_tolerates_missing,
        test_records_are_one_json_object_per_line,
    ]
    failures = 0
    for test in tests:
        try:
            test()
            print(f"PASS {test.__name__}")
        except AssertionError as e:
            failures += 1
            print(f"FAIL {test.__name__}: {e}")
    if failures:
        sys.exit(f"\n{failures}/{len(tests)} test(s) failed.")
    print(f"\nAll {len(tests)} tests passed.")


if __name__ == "__main__":
    main()
